os: ["ubuntu-latest"]
build:
  - target: "x86_64-unknown-linux-gnu"
    cc: "gcc"
    goos: "linux"
    goarch: "amd64"
  - target: "aarch64-unknown-linux-gnu"
    cc: "aarch64-linux-gnu-gcc"
    goos: "linux"
    goarch: "arm64"
service:
  - "aliyun-drive"
  # - "alluxio"
  # - "atomicserver"
  - "azblob"
  # - "azdls"
  # - "azfile"
  # - "b2"
  # - "cacache"
  # - "chainsafe"
  # - "cloudflare-kv"
  # - "compfs"
  # - "cos"
  # - "d1"
  # - "dashmap"
  # - "dbfs"
  # - "dropbox"
  # - "etcd"
  # - "foundationdb"
  - "fs"
  # - "ftp"
  - "gcs"
  - "gdrive"
  # - "ghac"
  # - "github"
  # - "gridfs"
  # - "hdfs-native"
  # - "http"
  # - "huggingface"
  # - "icloud"
  # - "ipmfs"
  # - "koofr"
  # - "libsql"
  # - "memcached"
  - "memory"
  # - "mini-moka"
  # - "moka"
  # - "mongodb"
  # - "mysql"
  # - "obs"
  # - "onedrive"
  - "oss"
  # - "pcloud"
  # - "persy"
  # - "postgresql"
  # - "redb"
  # - "redis"
  # - "redis-native-tls"
  # - "rocksdb"
  - "s3"
  # - "seafile"
  # - "sftp"
  # - "sled"
  # - "sqlite"
  # - "supabase"
  # - "surrealdb"
  # - "swift"
  # - "tikv"
  # - "upyun"
  # - "vercel-artifacts"
  # - "vercel-blob"
  # - "webdav"
  # - "webhdfs"
  # - "yandex-disk"

